# Generated by Django 5.2.4 on 2025-07-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="users.shopprofile",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvitation",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to="users.shopprofile",
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="shops",
            field=models.ManyToManyField(
                blank=True, related_name="suppliers", to="users.shopprofile"
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="suppliers.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="supplyentry",
            name="quotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="suppliers.quotation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quotation",
            unique_together={("supplier", "shop", "item", "created")},
        ),
    ]
