# Generated by Django 5.2.4 on 2025-07-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customer",),
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.shopprofile",),
        ),
    ]
