# Generated by Django 5.2.4 on 2025-07-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.shopprofile",
            ),
        ),
        migrations.AddField(
            model_name="cow",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cows",
                to="users.shopprofile",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="users.shopprofile",
            ),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplierprofile",
            ),
        ),
        migrations.AddField(
            model_name="stockexit",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exits",
                to="inventory.item",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("shop", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("shop", "sku")},
        ),
    ]
