# Generated by Django 5.2.4 on 2025-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_description_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
