# Generated by Django 5.2.4 on 2025-07-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_last_updated_item_unit'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexit',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exits', to='orders.order'),
        ),
    ]
