# Generated by Django 5.2.4 on 2025-07-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CowInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[("pre", "Pre-Slaughter"), ("post", "Post-Slaughter")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_fit_for_consumption", models.BooleanField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "cow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="inventory.cow",
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        limit_choices_to={"role": "vet"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("cow", "vet", "inspection_type")},
            },
        ),
        migrations.CreateModel(
            name="SlaughterApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField()),
                ("comments", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slaughter_approval",
                        to="inventory.cow",
                    ),
                ),
                (
                    "vet",
                    models.ForeignKey(
                        limit_choices_to={"role": "vet"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-approved_at"],
                "unique_together": {("cow",)},
            },
        ),
    ]
